# Generated by Django 5.1.6 on 2025-02-26 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mining", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="Hours",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="machine",
            name="Location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="machine",
            name="OperatingStatus",
            field=models.CharField(
                choices=[
                    ("Operational", "Operational"),
                    ("Maintenance", "Maintenance"),
                    ("Down", "Down"),
                ],
                default="Operational",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="ManufacturerID",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mining.manufacturer"
            ),
        ),
    ]
