# Generated by Django 5.1.6 on 2025-02-26 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mining", "0002_machine_hours_machine_location_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="machine",
            name="Hours",
        ),
        migrations.RemoveField(
            model_name="machine",
            name="Location",
        ),
        migrations.RemoveField(
            model_name="machine",
            name="OperatingStatus",
        ),
        migrations.AlterField(
            model_name="machine",
            name="ManufacturerID",
            field=models.IntegerField(),
        ),
    ]
